### ISSUE TITLE
Game functionality frozen

### ISSUE THREAD

**Issue by samsisle** [jacobabrennan/Goblinlike#10]
![screenshot 25](https://user-images.githubusercontent.com/28912696/46777772-8e21bf00-ccc5-11e8-945c-2688a877fb6a.png)

![screenshot 29](https://user-images.githubusercontent.com/28912696/46778119-02a92d80-ccc7-11e8-832e-f9d49995cb2e.png)

![screenshot 30](https://user-images.githubusercontent.com/28912696/46778126-08067800-ccc7-11e8-949d-fa87e66fe6f9.png)

On attempt to save a goblin stuck within a dungeon (stuck infinitely attacking mold that's completely surrounding him) previous previous to this one (shown in the screenshots), that previous previous dungeon was labeled as blocked so I decided to continue on. Screen froze upon entering new dungeon. 

dungeon (blocked) -> dungeon -> dungeon (froze here)

Only the "space" and "[" buttons are working. Thanks Jacob!

**Comment by jacobabrennan** [comment]
Fixed: Enemies removed from the map could crash the game by attempting to path to locate targets on the map.
